pin34 raw transmission
aisvn-data/solarpower pull request #4
Opened 2020-12-03 13:31 UTC by aisvn-data

2020-12-04 06:45 UTC, kreier reviewed
In general a good extention.

2020-12-04 06:45 UTC, kreier commented on software/SolarAISVN/SolarAISVN.ino
> +                      + "\",\"value3\":\"" + int((batValue * 0.826 + 150) * 2) + "\"}";
Adding conversion factors and calculation into the generation of the json object is probably not a good idea.

2020-12-04 06:45 UTC, kreier commented on software/SolarAISVN/SolarAISVN.ino
> +  digitalWrite(LED_BUILTIN, HIGH);
Short optical feedback of operation and wifi transmission is a good idea.

2020-12-04 06:45 UTC, kreier commented on software/SolarAISVN/SolarAISVN.ino
> +  delay(1000);
Is this time period to short? Could you write a blink() function?

2020-12-04 07:05 UTC, kreier commented on software/SolarAISVN/SolarAISVN.ino
> +int ledPin = 5;
Data array is a good solution instead of 8 distinctive voltage names!

2020-12-04 07:05 UTC, kreier commented on software/SolarAISVN/SolarAISVN.ino
> +  }
Deep sleep relocated?

2020-12-04 07:05 UTC, kreier commented on software/SolarAISVN/SolarAISVN.ino
> +                          + "\",\"value3\":\"" + voltage[6] + "|||" + voltage[7] + "|||" +bootCount + "\"}";
Nice structure to create the object.

2020-12-04 07:05 UTC, kreier commented on software/SolarAISVN/SolarAISVN.ino
> +void measureVoltages() {
Good inclusion to create a separate function!

2020-12-09 12:48 UTC, kreier requested changes

2020-12-09 12:48 UTC, kreier commented on software/SolarAISVN/SolarAISVN.ino
> +uint64_t TIME_TO_SLEEP = 60;
That's data submission every minute, not 120 seconds!

2020-12-09 12:48 UTC, kreier commented on software/SolarAISVN/SolarAISVN.ino
> +int zeit = millis();
Is this german?

2020-12-09 12:48 UTC, kreier commented on software/SolarAISVN/SolarAISVN.ino
> +  voltage[6] = int( (voltage[6] / 10 * 0.826 + 150 ) * 2);
Why pin 13 only 10 times?

2020-12-09 12:48 UTC, kreier commented on software/SolarAISVN/SolarAISVN.ino
> +  voltage[5] = int( (voltage[5] / 100 * 0.826 + 150 ) * 2);
Why now 100 times? Same pin 13?

2020-12-11 16:29 UTC, kreier commented on software/SolarAISVN/SolarAISVN.ino
> +                          + "\",\"value3\":\"" + voltage[6] + "|||" + voltage[7] + "|||" + voltage[8]
Now 8 values submitted?

2020-12-11 16:29 UTC, kreier commented on software/SolarAISVN/SolarAISVN.ino
> +// solar, battery, currentA, currentB, load, wind, dump, solar2, LiPo
Added documentation is good.

2020-12-11 16:29 UTC, kreier commented on software/SolarAISVN/SolarAISVN.ino
> +  voltage[8] = int((voltage[8]) * 1.608 + 258);         // pin13 LiPo     voltage divider 100kOhm 2:1
This new structure is so much easier to comprehend.

2020-12-11 16:39 UTC, kreier approved these changes

2020-12-11 16:39 UTC, kreier commented on software/SolarAISVN/SolarAISVN.ino
Good to have the names updated. And version included, as well as revision number.

2020-12-11 16:39 UTC, kreier commented on software/SolarAISVN/SolarAISVN.ino
> -
No need since we use only the ESP32, not ESP8266

2020-12-11 16:39 UTC, kreier commented on software/SolarAISVN/SolarAISVN.ino
> -  #endif
As mentioned above, we only use the ESP32, so the case ESP8266 needs not to be considered.

2020-12-11 16:39 UTC, kreier commented on software/SolarAISVN/SolarAISVN.ino
> -  // raw and converted voltage reading
too simple

2020-12-11 16:39 UTC, kreier commented on software/SolarAISVN/SolarAISVN.ino
> -                      + (bme.readPressure()/100.0F) + "\",\"value3\":\"" + bme.readHumidity() + "\"}";*/
This is just old data and structure

2020-12-11 16:42 UTC, aisvn-data reviewed
This version v0.5 should work fine.

2020-12-11 16:42 UTC, aisvn-data commented on software/SolarAISVN/SolarAISVN.ino
Now the values are converted and submitted as integer.

2020-12-11 16:42 UTC, aisvn-data commented on software/SolarAISVN/SolarAISVN.ino
> +  delay(1000);
Blink to indicate activity

2020-12-11 16:44 UTC, merged